# Generated by Django 5.2.3 on 2025-06-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='es_correcta',
            new_name='correcta',
        ),
        migrations.AddField(
            model_name='bancodepreguntas',
            name='cantidad_preguntas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='quizz.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('numero_preguntas', models.IntegerField(blank=True, null=True)),
                ('grupos', models.ManyToManyField(related_name='pruebas', to='quizz.grupo')),
            ],
        ),
    ]
