# Generated by Django 5.2.3 on 2025-06-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_remove_estudiante_grupo_grupo_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tiempo', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='bancodepreguntas',
            name='parametro_tiempo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizz.parametrotiempo'),
        ),
    ]
