# Generated by Django 5.2.3 on 2025-07-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_parametrotiempo_bancodepreguntas_parametro_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='banco_preguntas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='quizz.bancodepreguntas'),
        ),
    ]
